### ISSUE TITLE
iLvL discrepancy between Blizzard UI and simpleilevel

### ISSUE THREAD

**Issue by zaphon** [scotepi/wow-simpleilevel#1]
For characters who don't have an artifact, and who have only a single weapon equipped, the iLvL display between the addon and Blizzard's UI are different.  This is because while you handle the scoring properly for artifact weapons, you do not use the same logic for normal weapons.  I made a simple change/patch to fix this which I am attaching.

[fix.patch.txt](https://github.com/scotepi/wow-simpleilevel/files/1366399/fix.patch.txt)

**Comment by scotepi** [comment]
Corrected as of #e0556bc 3.4.0-alpha
