### ISSUE TITLE
Bad calcul with prodigious weapon.

### ISSUE THREAD

**Issue by totodu68** [scotepi/wow-simpleilevel#3]
The ilvl of the character is false in case he uses a prodigious weapon.
In the case of a prodigious weapon, the calculation to be done is to add the ilvl of all the objects and twice the ilvl of the weapon. All to divide by 16 regardless of the type of weapon equipped (weapon in 2 parts or not). To correct the problem, it would be enough to apply the right formula as soon as the weapon exceeds the 750 of ilvl.

**Comment by scotepi** [comment]
This should be resolved as of e0556bc or 3.4.0-alpha
