### ISSUE TITLE
8.0 Update

### ISSUE THREAD

**Issue by Gorthezar** [scotepi/wow-simpleilevel#4]
I know this addon hasn't been touched in a hot minute but any chance of a update for 8.0 BfA

**Comment by scotepi** [comment]
I have a TOC bump to put out but haven't looked into scaling the colors yet, that will most likely be an alpha tonight. Beta, when I get BfA iLevels, entered

**Comment by scotepi** [comment]
Version [3.3.16-alpha](https://wow.curseforge.com/projects/simple-ilevel/files) is building.

**Comment by Torsin** [comment]
Probably need to update Ace3 to the latest release and callbackhandler.  I tossed a ilevel table in the curse comment section, might have changed the colors at some point though.

**Comment by scotepi** [comment]
Release 3.3.16-beta, waiting for curse to rebuild

**Comment by scotepi** [comment]
Should be all set with 3.4.0-alpha or hopefully beta soon
