### ISSUE TITLE
[3.3.16-beta] Could not open CallbackHandler-1.0.xml

### ISSUE THREAD

**Issue by ghost** [scotepi/wow-simpleilevel#6]
Error: 
```Couldn't open SimpleILevel\Libs\CallbackHandler-1.0-7\CallbackHandler-1.0.xml```

Your script is looking for...
 ```..\SimpleILevel\Libs\CallbackHandler-1.0-7\CallbackHandler-1.0.xml```

...but your file structure is
```..\SimpleILevel\Libs\CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.xml```

**Comment by TanerH** [comment]
Came here to report this, too.  Simple fix to embeds.xml

**Comment by scotepi** [comment]
Fixed in 615d267 and will be in 3.4.0-beta
